version: "3"

services:
  nodeos:
    image: eosio/eos:v1.4.2
    volumes:
      - ./contract:/project
    working_dir: /project/
    ports:
      - "5555:5555"
      - "7777:7777"
    stop_signal: SIGKILL
    command: /bin/bash -c "keosd --http-server-address=0.0.0.0:5555 & exec nodeos -e -p eosio --plugin eosio::producer_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:7777 --access-control-allow-origin=* --contracts-console --http-validate-host=false --filter-on='*'"
    tty: true
  mm-server:
    image: node:8-alpine
    depends_on:
      - nodeos
    volumes:
      - ./server:/project
    working_dir: /project
    ports:
      - "3000:3000" # webpack-serve http
    command: ash -c "yarn install && yarn start"
    stop_signal: SIGKILL
    tty: true
