#!/bin/bash

set -x

cleos wallet create -f wallet-password
PW=$(cat wallet-password)
cleos wallet open
cleos wallet unlock --password $PW
cleos wallet create_key | awk -F\" '{ print $2 }' > public-key
PK=$(cat public-key)
cleos wallet import --private-key 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3

cleos create account eosio mobilitymkt $PK -p eosio@active


cleos create account eosio bob $PK -p eosio@active
cleos create account eosio alice $PK -p eosio@active

cd mobilitymkt
make deploy
