#!/bin/bash

# set -e
set -x

source ../mm-env
# #alias cleos='/opt/eosio/bin/cleos --url http://nodeos:7777 --wallet-url http://nodeos:5555'
# cleos() {
#     echo /opt/eosio/bin/cleos --url http://nodeos:7777 --wallet-url http://nodeos:5555 "$@"
#     /opt/eosio/bin/cleos --url http://nodeos:7777 --wallet-url http://nodeos:5555 "$@"
# }
# export -f cleos


# [[ # alice
ALICE_PK="EOS55ekz5AoJuq3SXQiv41rxg967ss8TaJDXBKUnjnFbnGQun97UP"
ALICE_SK="5Kcra1qW1PzVt4VZfzyPb5n6dDqL4BzEsNRer6JirSWsDzUNTie"
#   ],[ # eosio
EOSIO_PK="EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"
EOSIO_SK="5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"
#   ],[ # scooter
SCOOTER_PK="EOS78yJxETkWfZF5Mjj4HQ5N5t6KnoCjnh767J1ufit7bVbL9EBSX"
SCOOTER_SK="5JN9KjDxu47SbwB4wMhaocyJiyHYqycix3FJPZVVRadASZRE8Qy"
#   ],[ #uber
UBER_PK="EOS7amNLHXsWpt4PfD8sBqEHDSEb15TqBaSE5Bb3TZXfGsRaqLzD9"
UBER_SK="5KhhkLBaWBchaL4NgfQ2vJiDhugDofLMfsWCBTbjH8Nr8CXXPAU"
#   ],[ # BOB
BOB_PK="EOS8ATbvBEtmr9vAArsZDQiKk3KnF644DVnisr94nNpGBvPaxEtjM"
BOB_SK="5JUtqDDRwRrd437Hd8xY7CPmQbU6DTj5nA1mKJgyPeYpMbhA1Jr"
#   ],[ # bart
BART_PK="EOS8aPszS6H4eD6zVnmVUeKHjGYxhhg1qg6w13Ey8xBRbu7qYu13v"
BART_SK="5KBBkdzPwEeHrkBVTiCgxmqHrdNV9yNCnpRuGktPSKF5YF476hU"
#   ],[
MOBILITYMKT_PK="EOS6f6BCVEk8GsyBJBfVtgmrcnF8wYiHQx4vGEqjBvJQ1KLheHGYR"
MOBILITYMKT_SK="5JUc3Z1rpSJaoT4PMvenoH6ZjwWvuFETcUDsgU2H2MbaRka6mn3"
  # ], [
EOSIOTOKEN_PK="EOS8j5Zf6zrAQu1a1Qjm9YTZtzzmWGPt6CgeCPnQBL4eHSofFAeSM"
EOSIOTOKEN_SK="5KWcaW31fSXqPqBB2euVd9KTUi8BMaprpJ9KpruNcpxiUzHHyXW"
#  ]
# ]

cleos wallet create -f wallet-password
PW=$(cat wallet-password)
cleos wallet open
cleos wallet unlock --password $PW

# eosio
cleos wallet import --private-key $EOSIO_SK
cleos wallet import --private-key $ALICE_SK
cleos wallet import --private-key $SCOOTER_SK
cleos wallet import --private-key $UBER_SK
cleos wallet import --private-key $BOB_SK
cleos wallet import --private-key $BART_SK
cleos wallet import --private-key $MOBILITYMKT_SK
cleos wallet import --private-key $EOSIOTOKEN_SK


cleos create account eosio mobilitymkt $MOBILITYMKT_PK -p eosio@active

cleos create account eosio alice $ALICE_PK -p eosio@active
cleos create account eosio bob $BOB_PK -p eosio@active
cleos create account eosio uber $UBER_PK -p eosio@active
cleos create account eosio scooter $SCOOTER_PK -p eosio@active
cleos create account eosio bart $BART_PK -p eosio@active

# eosio.token
cleos create account eosio eosio.token $EOSIOTOKEN_PK -p eosio@active
cleos set contract eosio.token /contracts/eosio.token -p eosio.token
cleos push action eosio.token create '["eosio","1000000000000.0000 SYS"]' -p eosio.token
cleos push action eosio.token issue '["alice","100000.0000 SYS","memo"]' -p eosio
cleos push action eosio.token issue '["bob","100000.0000 SYS","memo"]' -p eosio

cleos set contract mobilitymkt /project/mobilitymkt --abi mobilitymkt.abi -p mobilitymkt@active
